# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Brushup' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Brushup
  pod 'React', :path => '../node_modules/react-native'
  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'BrushupTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Brushup-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Brushup-tvOS

  target 'Brushup-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
